// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRTjBoGeC9N4jJhuWuBUD_J0mkwv3x4vc',
    appId: '1:305234763309:web:cf8671902fb184a7ce22a4',
    messagingSenderId: '305234763309',
    projectId: 'tailor-desk-a1b7a',
    authDomain: 'tailor-desk-a1b7a.firebaseapp.com',
    storageBucket: 'tailor-desk-a1b7a.firebasestorage.app',
    measurementId: 'G-HZLMZCERM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhqTyxKBL_O9aFAnaLCI03z9VOEfspkJs',
    appId: '1:305234763309:android:5fd878309d2d78efce22a4',
    messagingSenderId: '305234763309',
    projectId: 'tailor-desk-a1b7a',
    storageBucket: 'tailor-desk-a1b7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtox_ljcM-4cO5iMzwJViDwVS9bRCq0Po',
    appId: '1:305234763309:ios:36e075c67b57d2a8ce22a4',
    messagingSenderId: '305234763309',
    projectId: 'tailor-desk-a1b7a',
    storageBucket: 'tailor-desk-a1b7a.firebasestorage.app',
    iosBundleId: 'com.example.tailorDeskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtox_ljcM-4cO5iMzwJViDwVS9bRCq0Po',
    appId: '1:305234763309:ios:36e075c67b57d2a8ce22a4',
    messagingSenderId: '305234763309',
    projectId: 'tailor-desk-a1b7a',
    storageBucket: 'tailor-desk-a1b7a.firebasestorage.app',
    iosBundleId: 'com.example.tailorDeskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRTjBoGeC9N4jJhuWuBUD_J0mkwv3x4vc',
    appId: '1:305234763309:web:14453947b8142044ce22a4',
    messagingSenderId: '305234763309',
    projectId: 'tailor-desk-a1b7a',
    authDomain: 'tailor-desk-a1b7a.firebaseapp.com',
    storageBucket: 'tailor-desk-a1b7a.firebasestorage.app',
    measurementId: 'G-XRYF0QB8VZ',
  );
}
